language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt -r requirements-dev.txt
before_script:
  - echo 'ok'
script:
  - nosetests --with-coverage
after_success:
  - coveralls
